/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package work;

public class FizzBuzz {
    public void doFizzBuzz() {
        for (int i = 1; i <= 100; i++) {
            String output = "";
            if (i % 3 == 0) {
                output += "Fizz";
            }
            if (i % 5 == 0) {
                output += "Buzz";
            }
            if (output.equals("")) {
                output = Integer.toString(i);
            }
            System.out.println(output);
        }
    }

    public static void main(String[] args) {
        new FizzBuzz().doFizzBuzz();
    }
}
